jwt:
  secret: ZHVtbXlzZWNyZXRrZXlmb3Jqd3R0b2tlbjEyMzQ1Njc4OTA=
  access-expiration-ms: 3600000
  refresh-expiration-ms: 604800000

spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      client:
        registration:
          instagram:
            client-id: 1199148131878666
            client-secret: 87f976749c42dfc966b922f429a836f9
            redirect-uri: https://localhost:3000/login/callback

  datasource:
    url: jdbc:mysql://211.188.54.189:13306/bizket_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dev_user
    password: BizketDev0412@@
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1500000

  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://211.188.54.189:13306/bizket_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test_user
    password: BizketDev0412@@

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        format_sql: true
        use_sql_comments: true
