spring:
  application:
    name: bizket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bizket?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kakao:
    auth:
      client: ${CLIENT_ID}
      redirect: ${REDIRECT_URI}

jwt:
  token:
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000
